export const GET_TWEET_DATA = "GET_TWEET_DATA";
export const GET_TWEET_DATA_ERROR = "GET_TWEET_DATA_ERROR";
export const GET_TWEET_DATA_RECEIVED = "GET_TWEET_DATA_RECEIVED";

export const GET_TWEET_DATA_AUTOUPDATING = "GET_TWEET_DATA_AUTOUPDATING";
export const GET_TWEET_DATA_AUTOUPDATING_ERROR = "GET_TWEET_DATA_AUTOUPDATING_ERROR";
export const GET_TWEET_DATA_AUTOUPDATING_RECEIVED = "GET_TWEET_DATA_AUTOUPDATING_RECEIVED";
